language: java
jdk: oraclejdk8
script: gradle/buildViaTravis.sh

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
notifications:
  email: false
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
  global:
  - secure: "w/nDOUHliKKFsEglHPJKwH1blV9gNw8KJrJgWV2MA4uNFiuGhksLWvehQ26AI4AMjD8ptNCkYrmR2DQf+c4v5fhz6IRiLw3LvKNCpG1J1SHK7gzOQzXV9HqEwO3naoVTrwne3h24Ehx4cpNijsnXtI8T0ZKsHA4XExyCenNzlPmU97x1+2JNfc0wiokg8AZ1MFoDb48JEQr7Qx6dNx1Yeanv6e+FMyLynxoERGe/9QtYr2TqCHhCSngqniwb7TLV/IYu2BeIrM+tZ41qW3T7ls/WUzOlR58nGEazVhjyXCDCrHwx+GYbblLxQmSoX+Dozvm1i1AnwCF24ZMcHr2pWWwnc1uF5e6RgSdLbqmOyEX09rAuYPui25+kFWZN5DknO+neB1JuWOVERvipL+BfrO5xSSFXvxKKLAaqBCfgiU0VkYQvMoVadN/PzKoLndNKJcMGlImWgCBPAYuhhxVDN6oAfBvt7egR/E78gPyJ9V3HziLuGLKqxF1oroEvkYsk/EQuDEDn3PLRA6tHiLrbnS+e8VW1BeHglIbPHmT5566/FWUoWFf7+g99xuP4PYtOG+clPz6SJ3excG+J5AbmfSRvW5jKnkmPsvirYdpZcWveAA2XDqYNNryRECDLrS3PNjIUyn6rjIe79xYp0vr91jZ8+/rg86hVYrpN1dUS0jY="
  - secure: "c26Z09ndi7HFQ7x0YmXURCVzg22l4StTDIwZcMVneip/bp/8WDDnbUgpsFW6s8DTKcwlYE4K/854VUj9NDfHYpNHC+vY2nKmqDFbaMRxlWOMWyu/xvhmRNPttD6fLW2NEg422HbABjg7fbPnlFUHMdx0qa72nbG4FnfUMJlGHnKp4O8AAba0xVVgQ7x76UERUqkgfh9iRSl5YHovXT+XPr3c/DiYDqrap3fs7NZ1n7RU/qvyTFwgiECvhF/8FA2pIZX8zQUZ0nc/z38JVolSYAaxNkkRxTlq+kJ/3j2k5kOijyO/CpHNESSlN07hB686nGB8CJb5M5gTEw+U/uKnVi6/oKCFQmebzQ5m/Sp6tUbtcuEI50LK37rN8v81Pno7nqJ7IweDTD6hDNkQaIRknkojw/mJY7zfGsEGpdNI7QexU3wNpKhp3z7eDeq/mz6zYkcbicP88wh8HtYCz+z+Pet+l0VV0RkdxohH67cZrHHY3i8/eacuelo3jlJeJ1hGvzUBLT4kkPICPHgVUYUpPL2JwzvYfMHI10lxHuOXGImExGyZ7x0IehKziQAI6QJ3msXYSG4zjpiUE18ExT0j02475O1QEQkCqWEggVYpLTsks+CqV1GXdxfVwWPLutzbGkdydaaUYIMJhDAQHrJNQCNGjH+y9PA4Wb8C/ON8Q+I="