language: java
jdk: oraclejdk8
script: ci/travis.sh

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
notifications:
  email: false
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
  global:
  - secure: "SZNz4YBQxkIe3RbOD7fUSS8LRDw5s0TfINUawUK2iUhUZ7v1Gccn3XQL82zpKHZ3a0n+5DyX5AZQwVBJ9sPVHStU175MOQMalAvy2Xzb+v+trrMO0qEm6/zi7pScHgpk65yeOjnOnAk6rDI1CGiDp4Hgq80O0n/9EaM418VPqtw3xkNTPyRE2+hvFzI4b/ioK6UazSUO/K6iijc5kSgo/F3ngirSHVvApklDD1Lgg/5/lAwFWjpOUErC69T6RCmcOH9V9Y2cXtvblbZYcAMG5fU3s8Tj+PUqBqRR+wONQIQbHEukNgZ+NTl5pdrFi1K0xYtmN0W1ziN9ibRepgcTBZ6qzTLCzTLeIDjVG2LBDEenWqX/AZrnpOh+RWM0HuQdwMuO5S7Suy5b0Hty/NfpZkRKmrs5BpD7wjUGfiPwvJhVnOhkYb5JVNzob0eahDKbPZuBHQ36Sg0OYNj/U1ySMf2dcWUH0xEfZaRDpPK1bJ6c2Q7WMfpmi1MJeqpAHm/9kCtThxnyOoTXG6Zt46mrLIgh5Mo6PLcItpuX2OA9QsQ/zUOdILqAfLABv2nfvZwlTOvocxwV/i2hRB9+Si/wJ92qBtiHBNUugG3ZB+qLeF1+6EvOkZwjXLUmVFlt53Fr/RvdPI8sXGRDGsw690/LgbbSTkuiL9bZj09TO9Dv/to="
  - secure: "p6QO5YHrZkQfoqqWwogmsILooHEAJiY3JFPQkkGUYxbKPqOQblEoi5YywSXT0InCTyl63Igs0He3Zq0f/avlM6vS2Qf1U8i78ASPUGFlFSfnAl7Z35e/zndB0tkmWN78C2CfeVjDjzbtUxoRFHjF7JMD9oi7JF69Nqk+Sey7wNP3bWNrF+teX241srjr4VfgFHPRzvw+Z72mVQgQvVae3UyqVokNLZpeynMiEMNRITkAnlrbvOD2yfiPUXIiN14u14nyZDd7knL2u3SB3Pn7khDHrDE4sp3DkWkDV1MRg7yJPD611NZIi1pkYEn+6mp20IQk3djoOfv6nlgKqQsIMn/yApTRu/TmLWim+PAyuEvRhUu94EJeRXCnYaU2Rwr4jJQrAaQdH/HpGI6Jvv+mPpNJAdHDJA+pEe+te0sTXmXOnax08vYlImwaYTEKpxXbMOpEHfA2wyUOPvI7+BghghgJQdttrMCVRImkUDdes/FAUrhBmGA2VuvZZads6XWV+uYAEQ9Mfp1Um1g64MZGWE9c8DjCTOHkd4gsJ9vYu6j58zTKPh7gHgbWfkVgJc0I181PLPtxA8K4fHjsGao/EgLyxxpmjkwvGpqpBC7//ACnG7it25N6cZPItqUpWxr5U/5GpqIdPS9/Enmy74BV0V7TOOUMgB+IVrYiKISg7LY="